name: demandium_provider
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  chewie: ^1.8.5
  connectivity_plus: ^6.0.5
  country_code_picker: ^3.0.0
  currency_text_input_formatter: ^2.2.3
  dotted_border: ^2.1.0
  expandable_bottom_sheet: ^1.1.1+1
  file_picker: ^8.1.2
  firebase_auth: ^5.2.1
  firebase_core: ^3.7.0
  firebase_crashlytics: ^4.1.1
  firebase_messaging: ^15.1.4
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_downloader: ^1.11.8
  flutter_inappwebview: ^6.1.4
  flutter_local_notifications: ^17.2.2
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^4.0.0
  flutter_switch: ^0.3.2
  flutter_typeahead: ^5.2.0
  flutter_widget_from_html_core: ^0.15.2
  geolocator: ^13.0.1
  get: ^4.6.6
  google_maps_flutter: ^2.9.0
  graphic: ^2.5.0
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  just_the_tooltip: ^0.0.12
  open_file_plus: ^3.4.1+1
  package_rename: ^1.8.0
  path: ^1.9.0
  path_provider: ^2.1.4
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  phone_numbers_parser: ^9.0.0
  photo_view: ^0.15.0
  pin_code_fields: ^8.0.1
  printing: ^5.13.2
  qr_code_scanner_plus: ^2.0.8+1
  readmore: ^3.0.0
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  shimmer_animation: ^2.2.1
  syncfusion_flutter_charts: ^27.2.2
  timelines_plus: ^1.0.6
  universal_html: ^2.2.4
  url_launcher: ^6.3.0
  video_player: ^2.9.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/Roboto-Light.ttf
          weight: 300
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
